spring:
  application:
    name: teatro-real-backend
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true

server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.teatroreal: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v1/docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
