# Configuración de la aplicación
spring.application.name=teatro-real-backend
server.port=

# Logging
logging.level.root=INFO
logging.level.com.teatroreal=DEBUG
logging.level.org.springframework.web=INFO

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Europe/Madrid
spring.jackson.locale=es_ES
